-- MySQL Script generated by MySQL Workbench
-- Tue May 26 23:33:21 2026
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`roles`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`roles` (
  `role_id` INT NOT NULL AUTO_INCREMENT,
  `role_name` VARCHAR(45) NULL,
  PRIMARY KEY (`role_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`users`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`users` (
  `user_id` INT NOT NULL AUTO_INCREMENT,
  `login` VARCHAR(45) NULL,
  `password` VARCHAR(45) NULL,
  `role_id` INT NULL,
  `full_name` VARCHAR(45) NULL,
  PRIMARY KEY (`user_id`),
  INDEX `FK_roles_idx` (`role_id` ASC) VISIBLE,
  CONSTRAINT `FK_roles`
    FOREIGN KEY (`role_id`)
    REFERENCES `mydb`.`roles` (`role_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`categories`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`categories` (
  `category_id` INT NOT NULL AUTO_INCREMENT,
  `category_name` VARCHAR(45) NULL,
  PRIMARY KEY (`category_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`manufactures`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`manufactures` (
  `manufacture_id` INT NOT NULL AUTO_INCREMENT,
  `manufacture_name` VARCHAR(45) NULL,
  PRIMARY KEY (`manufacture_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`suppliers`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`suppliers` (
  `supplier_id` INT NOT NULL AUTO_INCREMENT,
  `supplier_name` VARCHAR(45) NULL,
  PRIMARY KEY (`supplier_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`units`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`units` (
  `unit_id` INT NOT NULL AUTO_INCREMENT,
  `unit_name` VARCHAR(45) NULL,
  PRIMARY KEY (`unit_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`products`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`products` (
  `product_id` INT NOT NULL AUTO_INCREMENT,
  `article` VARCHAR(45) NULL,
  `product_name` VARCHAR(45) NULL,
  `category_id` INT NULL,
  `description` VARCHAR(100) NULL,
  `manufacturer_id` INT NULL,
  `supplier_id` INT NULL,
  `price` INT NULL,
  `unit_id` INT NULL,
  `quantity` INT NULL,
  `discount` INT NULL,
  `image_path` VARCHAR(45) NULL,
  PRIMARY KEY (`product_id`),
  INDEX `FK_manufacture_idx` (`manufacturer_id` ASC) VISIBLE,
  INDEX `FK_supplier_idx` (`supplier_id` ASC) VISIBLE,
  INDEX `FK_unit_idx` (`unit_id` ASC) VISIBLE,
  INDEX `FK_category_idx` (`category_id` ASC) VISIBLE,
  CONSTRAINT `FK_manufacture`
    FOREIGN KEY (`manufacturer_id`)
    REFERENCES `mydb`.`manufactures` (`manufacture_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `FK_supplier`
    FOREIGN KEY (`supplier_id`)
    REFERENCES `mydb`.`suppliers` (`supplier_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `FK_unit`
    FOREIGN KEY (`unit_id`)
    REFERENCES `mydb`.`units` (`unit_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `FK_category`
    FOREIGN KEY (`category_id`)
    REFERENCES `mydb`.`categories` (`category_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`order_status`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`order_status` (
  `status_id` INT NOT NULL AUTO_INCREMENT,
  `status_name` VARCHAR(45) NULL,
  PRIMARY KEY (`status_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`pickup_points`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`pickup_points` (
  `pickup_point_id` INT NOT NULL AUTO_INCREMENT,
  `address` VARCHAR(45) NULL,
  PRIMARY KEY (`pickup_point_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`orders`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`orders` (
  `order_id` INT NOT NULL AUTO_INCREMENT AUTO_INCREMENT,
  `product_id` INT NULL,
  `status_id` INT NULL,
  `pickup_point_id` INT NULL,
  `order_date` DATE NULL,
  `delivery_date` DATE NULL,
  `user_id` INT NULL,
  PRIMARY KEY (`order_id`),
  INDEX `FK_product_idx` (`product_id` ASC) VISIBLE,
  INDEX `FK_status_idx` (`status_id` ASC) VISIBLE,
  INDEX `FK_pickup_point_idx` (`pickup_point_id` ASC) VISIBLE,
  INDEX `FK_user_idx` (`user_id` ASC) VISIBLE,
  CONSTRAINT `FK_product`
    FOREIGN KEY (`product_id`)
    REFERENCES `mydb`.`products` (`product_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `FK_status`
    FOREIGN KEY (`status_id`)
    REFERENCES `mydb`.`order_status` (`status_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `FK_pickup_point`
    FOREIGN KEY (`pickup_point_id`)
    REFERENCES `mydb`.`pickup_points` (`pickup_point_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `FK_user`
    FOREIGN KEY (`user_id`)
    REFERENCES `mydb`.`users` (`user_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
